### ISSUE TITLE
Pagina web del glossario

### ISSUE THREAD

**Issue by lucaribon** [CodeHex16/codehex16.github.io#2]
Controllare anche che i link al glossario, puntati dalle definizioni in giro per i documenti, funzionino.

**Comment by bazz333** [comment]
ora la pagina web ha una pagina "glossario", che viene popolata automaticamente a partire dal file `glossario.typ`
le github action prendono il file `glossario.typ` e copiano il contenuto a partire dal commento `//GLOSSARIO` in giù in `glossario.txt` che viene poi pushato nell'altra repository.
viene poi letto usato dal file `glossario.js` per aggiungere le definizioni.
vengono mostrate solo le lettere contengono definizioni.
